name: Airdrop
main: lukemccon.airdrop.Airdrop
version: 3.0
api-version: '1.20'
depend:
  - LuckPerms
  - Essentials
commands:
    airdrop:
        aliases: [drop, ad]
        description: Call in an airdrop!
        usage: /airdrop <package name>
developers:
  - LukeMccon
  - pianoman99987 (gregoryw)
