name: Airdrop
main: com.airdropmc.Airdrop
version: 3.2
api-version: '1.20'
depend:
  - LuckPerms
  - Essentials
  - Vault
commands:
    airdrop:
        aliases: [drop, ad]
        description: Call in an airdrop!
        usage: /airdrop <package name>
developers:
  - LukeMccon
  - pianoman99987 (gregoryw)
