name: Release
on:
  push:
    branches:
      - main-fix
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     release_branches: main
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
      #     artifacts: target/*.jar
      #     makeLatest: true# This workflow will build a Java project with Maven
  build:

    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: ossrh
        server-username: ${{ env.MAVEN_USERNAME }}
        server-password: ${{ env.MAVEN_PASSWORD }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ env.MAVEN_GPG_PASSPHRASE }}
    - name: Import GPG key and passphrase
      run: |
        echo "${{ secrets.MAVEN_GPG_PASSPHRASE }}" | gpg --batch --passphrase-fd 0 --import  ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    - name: Deploy with Maven
      run: mvn --no-transfer-progress --batch-mode -DperformRelease=true -Prelease-sign-artifacts -s .github/settings.xml -B clean deploy 
