# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Install and unit test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download Maven
      run: |
        if [ ! -f "/usr/bin/mvn" ]; then
        sudo curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
        sudo apt-get update
        sudo apt-get -y install unzip
        unzip -d /usr/share maven.zip
        rm maven.zip
        ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
        else
          echo "Skipping maven installation, already found"
        fi
    - name: Install less
      run: sudo apt-get update; sudo apt install less
    - name: Install aws cli
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2     # default
        verbose: false # default
        arch: amd64    # allowed values: amd64, arm64
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Download spigot-api.jar for buildpath
      run: aws s3api get-object --bucket airdrop-spigot-plugin --key spigot-api.jar ./spigot-api.jar
    - name: Install spigot as mvn dependency
      run: |
        mvn install:install-file \
             -Dfile=./spigot-api.jar \
             -DgroupId=me.lukemccon.spigot \
             -DartifactId=spigot \
             -Dversion=1.0 \
             -Dpackaging=jar \
             -DgeneratePom=true \

    - name: Resolve dependencies
      run: mvn dependency:resolve

    - name: Run Unit test
      run: mvn test
